#!/usr/bin/env node
/* ------------------------------------------------------------
   SANCTUARY · secure edition — env generator
   Reads secrets from environment variables (or a local .env)
   and writes env.js (gitignored) that the browser loads.
   Usage:
     node api/generate-env.js                 # reads process env / .env
     SUPABASE_URL=... SUPABASE_ANON_KEY=... node api/generate-env.js
------------------------------------------------------------ */
"use strict";
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");

// tiny .env loader (no dependencies)
const envFile = path.join(root, ".env");
if (fs.existsSync(envFile)) {
  for (const line of fs.readFileSync(envFile, "utf8").split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)\s*$/);
    if (m && process.env[m[1]] === undefined) process.env[m[1]] = m[2].replace(/^["']|["']$/g, "");
  }
}

const REQUIRED = ["SUPABASE_URL", "SUPABASE_ANON_KEY"];
const missing = REQUIRED.filter((k) => !process.env[k]);
if (missing.length) {
  console.error("✗ Missing required env vars: " + missing.join(", "));
  if (process.env.VERCEL) {
    console.error("  Add them in Vercel → Project → Settings → Environment Variables");
    console.error("  (Production + Preview), then redeploy.");
  } else {
    console.error("  Copy .env.example to .env, fill it in, then re-run this script.");
  }
  process.exit(1);
}

if (!/^https:\/\/[a-z0-9-]+\.supabase\.(co|in)$/.test(process.env.SUPABASE_URL)) {
  console.error("✗ SUPABASE_URL must look like https://your-project.supabase.co");
  process.exit(1);
}

// ------------------------------------------------------------
// SITE_USERS — the named login identities shown on the gate.
//   1. "for babieee"  → read-only viewer (no edit rights)
//   2. "aryan"        → read-only viewer (no edit rights)
//   3. "admin"        → full backend edit power
// Passwords are NOT stored here — they live (hashed) in Supabase
// Auth → Authentication → Users. SANCTUARY_PASSWORD_HASH is an
// OPTIONAL legacy fallback passcode for the old SHA-256 gate.
// Configure as:  SITE_USERS='[{"label":"for babieee","email":"babieee@example.com"},{"label":"aryan","email":"aryan@example.com"},{"label":"admin","email":"admin@example.com"}]'
// ------------------------------------------------------------
let siteUsers = [];
try {
  siteUsers = JSON.parse(process.env.SITE_USERS || "[]");
  if (!Array.isArray(siteUsers)) throw new Error("not an array");
  siteUsers = siteUsers
    .filter((u) => u && typeof u.label === "string" && typeof u.email === "string" && u.label && u.email)
    .map((u) => ({ label: String(u.label).slice(0, 40), email: String(u.email).trim().toLowerCase() }));
} catch (e) {
  console.error("✗ SITE_USERS must be a JSON array like: " +
    '[{"label":"for babieee","email":"..."},{"label":"aryan","email":"..."},{"label":"admin","email":"..."}]');
  process.exit(1);
}
if (siteUsers.length === 0 && !process.env.SANCTUARY_PASSWORD_HASH) {
  console.error("✗ No logins configured. Set SITE_USERS (recommended) or SANCTUARY_PASSWORD_HASH (legacy fallback).");
  process.exit(1);
}

const out = `/* generated by api/generate-env.js — DO NOT COMMIT */
window.SANCTUARY_CONFIG = {
  SUPABASE_URL: ${JSON.stringify(process.env.SUPABASE_URL)},
  SUPABASE_ANON_KEY: ${JSON.stringify(process.env.SUPABASE_ANON_KEY)},
  SITE_USERS: ${JSON.stringify(siteUsers)},
  SANCTUARY_PASSWORD_HASH: ${JSON.stringify(process.env.SANCTUARY_PASSWORD_HASH || "")},
  DEBUG: ${process.env.DEBUG === "true"},
  DEPLOYED_AT: ${JSON.stringify(new Date().toISOString())}
};
`;

fs.writeFileSync(path.join(root, "env.js"), out);
console.log("✓ env.js generated (gitignored). Site is ready to open.");
console.log(`  Logins: ${siteUsers.map((u) => u.label).join(", ") || "(legacy passcode only)"}`);
